export const Upcoming = [];

export const Past  = [
    { date: '31.10.2016', description: ' Revolver, Oslo, Norway, with Angelcorpse (US) ' },
{ date: '07-08.10.2016', description: ' Old Grave Fest V, Bucuresti, Romania '},
{ date: 'June 2016', description : 'European tour with DHG',
    gigs: [
    { date: '18.06.2016', description: ' Copenhagen, Denmark - Pumpehuset'},
    { date: '19.06.2016', description: ' Poznan, Poland - U Bazyla'},
    { date: '20.06.2016', description: ' Erfurt, Gemany - From Hell Club'},
    { date: '21.06.2016', description: ' Vienna, Austria - Viper Room'},
    { date: '22.06.2016', description: ' Antwerpen, Belgium - Kavka'},
    { date: '23.06.2016', description: ' Lille, France - El Diablo Club'},
    { date: '24.06.2016', description: ' Arnhem, The Netherlands - Willemeen'},
    { date: '25.06.2016', description: ' Oberhausen, Germany - Helvete'}
    ]},
{ date: '25-27.03.2016', description: ' WitchFest, Johannesburg, South Africa.  '},
{ date: '29.01.2016', description: ' Mono Goes Metal Festival, Århus, Denmark.  '},
{ date: '11.12.2015', description: ' Pokalen, Oslo, Norway, with Demilich and Gouge.'},
{ date: '20.06.2015', description: ' Saturday, Massive Destruction Fest Kickoff, Drammen, Norway. '},
{ date: '13.06.2015', description: ' Saturday,Sczcecin Extreme Fest, Szczecin, Poland.  '},
{ date: '11.06.2015', description: ' Thursday, Klub Ciemna Strona Miasta, Wroclav, Poland, together with Maze and Coherence. '},
{ date: '27.03.2015', description: ' Friday, G60, Drammen. '},
{ date: '27.11.2014', description: ' Thursday, Blitz, Oslo, together with Dysmorfic (it) and Higgs Boson (no). '},
{ date: '24.10.2014', description: ' Friday, Kolben, Kolbotn, Norway, together with Obliteration and Execration.'},
{ date: '27.09.2014', description: ' Saturday, Pokalen, Oslo, Norway. Oscillations release gig! Support: Lobotomized and Morbo (it).'},
{ date: '26.09.2014', description: ' Friday, Seb\'s Hotel, Hamar, Norway, together with Deathhammer and Morbo.'},
{ date: '20.09.2014', description: ' Saturday, Fru Lundgreen, Trondheim, Norway. Support: Dumhetens Hær and Infant Death.'},
{ date: '01.03.2014,', description: 'Saturday, Revolver, Oslo, Norway, at the by:Larm festival.' },
{ date: '27.02.2014,', description: 'Thursday, John Dee, Oslo, Norway, at the by:Larm festival.' },
{ date: '01.11.2013,', description: 'Friday, Betong, Oslo, Norway. South of Heaven Club 10th Anniversary festival. Other acts include CORONER, KATECHON, NOCTURNAL BREED and DRAGGED INTO SUNLIGHT. ' },
{ date: '30.03.2013,', description: 'Saturday, Inferno Metal Festival 2013, 22:15 at John Dee stage.' },
{ date: '08.12.2012,', description: 'Saturday, Revolver, Oslo, Norway, together with Grotesque Hysterectomy and Execration ' },
{ date: '01.12.2012,', description: 'Saturday, Seb\'s, Hamar, Norway, together with Grotesque Hysterectomy and Execration ' },
{ date: '30.11.2012,', description: 'Friday, Fru Lundgreens, Trondheim, Norway together with Grotesque Hysterectomy and Execration ' },
{ date: '23-30.06.2012',
    description: ' Dystopic Odes of Norway: Diskord and Execration European tour. Shows:',
    gigs: [
     { date: '22.06.2012', description: ' Italy, Bologna @ XM24 w/ NASUM + WORMROT. '},
     { date: '23.06.2012', description: ' Germany, Memmingen @ Schwarzer Adler "Mosh Against Southside IV" w/ FLESHCRAWL + ENDDARM. '},
     { date: '25.06.2012', description: ' Czech Republic, Breclav @ Piksla Kafe. '},
     { date: '26.06.2012', description: ' Czech Republic, Prague @ Exit-us w/ POSSESSED (usa) + PANDEMIA. '},
     { date: '27.06.2012', description: ' Germany, Berlin @ Koma-F. '},
     { date: '28.06.2012', description: ' Germany, Neu-Anspach @ Juz Alt-Anspach w/ WOMB LEECH. '},
     { date: '30.06.2012', description: ' Italy, Milan @ Blue Rose Saloon w/ NECRO + GRINDZERO. '}
    ]},
{ date: '03.04.2012', description: ' DYSTOPICS RELEASE PARTY, at Unholy, Oslo. Ghoul Cult will be supporting us. '},
{ date: '30.09-01.10.2011', description: ' Til Dovre Faller Festival, DombÃ¥s, Norway.'},
{ date: '01-03.09.2011', description: ' Kill-Town Death Fest, Copenhagen, Denmark.'},
{ date: '24-27.08.2011', description: ' Hole In The Sky Festival, Bergen, Norway. We will be playing on the Assault Stage at Garage on Saturday, with Vomitor and Nekromantheon.'},
{ date: '20-23.04.2011', description: ' The Inferno Festival, John Dee, Oslo. Check www.infernofestival.net for the full details.'},
{ date: '23-24.10.2010', description: ' Live Evil Festival, Cambden Underworld, London, UK.'},
{ date: '30.04.2010', description: ' Truckstop Alaska, Gothenburg, Sweden, Together with Obliteration and Karnarium.	'},
{ date: '24.04.2010', description: ' Oslo We Rot! Combined release party and gig together with Obliteration, Execration and Lobotomized.'},
{ date: '23.01.2010', description: ' Inferno Festival Kick Off @ Fru Lundgren, Trondheim. Together with Obliteration and Resonaut.'},
{ date: '19.07.2008', description: ' Slottsfjell festival, TÃ¸nsberg, together with (amongst others) 1349, Blood Red Throne, De Lillos, Gogol Bordello and Kent. Check www.slottsfjellfestival.no for the full details.'},
{ date: '18.04.2008', description: ' Oslo Death Fest, Club Maiden, Oslo, together with The Allseeing I, Deject and The Sickening.'},
{ date: '19.03.2008', description: ' The Inferno Festival, Rock In, Oslo. Check www.infernofestival.net for the full details.'},
{ date: '17.11.2007', description: ' Tribute, Sandnes, together with Abominat and Grotesque Hysterectomy.'},
{ date: '16.11.2007', description: ' På Hjørnet, Kristiansand, together with Abominat and Grotesque Hysterectomy.'},
{ date: '25.05.2007', description: ' Scene 37, Horten, together with She Said Destroy and Execration.'},
{ date: '20.04.2007', description: ' Club Maiden, Oslo, together with Abominat and Grotesque Hysterectomy.'},
{ date: '04.04.2007', description: ' Elm Street, Oslo, together with She Said Destroy and Manngard.'},
{ date: '16.03.2007', description: ' Rivals, TÃ¸nsberg, together with She Said Destroy and Execration.'},
{ date: '18.10.2005', description: ' Garage, Oslo, together with noplacetohide.'},
{ date: '02.07.2005', description: ' Skuret, Oslo, together with Watain and Ghastly. '},
{ date: '10.09.2004', description: ' South of Heaven #8, Betong, Chateau Neuf, Oslo, together with Chton.'},
{ date: '23.06.2004', description: ' Riggen, Drammen, together with Imbalance.'},
{ date: '24.04.2004', description: ' Byscenen, Trondheim, together with Cadaver and Klompfot '},
{ date: '20.03.2004', description: ' Skuret, Grønland, Oslo, together with Minas Tirith and Vesen.'},
{ date: '21.11.2003', description: ' Kulturlåven, Asker, together with Zyklon and She Said Destroy. '},
{ date: '24.10.2003', description: ' The Sement Festival, Betong, Oslo, together with Tömmermenn, Tidfall ++'},
{ date: '15.08.2003', description: ' Victoria Kulturhus, Drammen, together with Koldbrann '},
{ date: '24.05.2003', description: ' Nyx, Oslo, together with Slavia and Disiplin.'},
{ date: '25.04.2003', description: ' Amatøren, Oslo, at the Band Festival.'},
{ date: '06.03.2003', description: ' Betong, Oslo, together with Nebular Mystic and MindGrinder'},
{ date: '07.12.2002', description: ' The Royal Oak, Tønsberg, together with Single Unit and noplacetohide.'},
];

